name: proper use
on: push

jobs:
  deploy_staging:
    runs-on: ubuntu_latest
    name: Staging
    env: 
      AWS_REGION: us-east-1
      CONTAINER_NAME: nice-app-service
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: Configure AWS cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
